name: PHP SYNTAX
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./HRM
    steps:
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.0
        with:
          dir: ./HRM
          working-directory: ${{env.working-directory}}
